language: 'java'

cache:
  directories:
    - '${HOME}/.m2/repository'

services:
  - 'docker'

env:
  global:
    - DOCKER_COMPOSE_VERSION: '1.27.4'
    - REDIS_VERSION: '6.0.9'
    - REDIS_SHA256: '2819b6d9c56be1f25cd157b9cb6b7c2733edcb46f4f6bcb1b79cefe639a2853b'
    - J2CLI_VERSION: '0.3.10'
    - DOCKERHUB_USER: 'abrarov'
    - MAVEN_WRAPPER: '0'
    - RELEASE_JOB: '0'
    - DOCKER_PUSH_RETRIES: '10'
    - DOCKER_MAVEN_PLUGIN_VERSION: '0.34-dev'
    - REDIS_START_TIMEOUT: '120'
    - REDIS_STOP_TIMEOUT: '120'

matrix:
  include:
    # OpenJDK 8
    - dist: 'trusty'
      jdk: 'openjdk8'
      env:
        - RELEASE_JOB: '1'
    # OpenJDK 8 with Maven Wrapper
    - dist: 'trusty'
      jdk: 'openjdk8'
      env:
        - MAVEN_WRAPPER: '1'
    # OpenJDK 11
    - dist: 'bionic'
      jdk: 'openjdk11'

before_install: 'bash travis/install-docker-compose.sh'

install: 'skip'

script: 'bash travis/build-and-test.sh'

deploy:
  skip_cleanup: true
  provider: 'script'
  script: 'bash travis/push-docker-images.sh'
  on:
    branch: 'master'
    condition: '${RELEASE_JOB} = 1'
