version: '2.1'

services:

  helper:
    image: '${IMAGE_REGISTRY:-abrarov}/redis-helper:${PROJECT_VERSION:-1.0.1}'
    read_only: true
    volumes:
      - '/helper'

  init:
    image: '${IMAGE_REGISTRY:-abrarov}/redis-init:${PROJECT_VERSION:-1.0.1}'
    command: '/helper/run.sh'
    environment:
      INIT_COMMAND: '/run.sh'
      REDIS_CONFIG_DIR: '/config'
      REDIS_PORT: '6379'
      REDIS_LISTEN_BACKLOG: '128'
      REDIS_PROTECTED_MODE: 'no'
      REDIS_DATA_DIR: '/data'
    read_only: true
    volumes:
      - '/tmp'
      - '/config'
    volumes_from:
      - 'helper:ro'

  redis:
    image: '${IMAGE_REGISTRY:-abrarov}/redis:${REDIS_VERSION:-6.0.9}-${PROJECT_VERSION:-1.0.1}'
    command:
      - '/helper/dockerize'
      - '-wait'
      - 'tcp://init:8080'
      - '-timeout'
      - '60s'
      - 'redis-server'
      - '/config/redis.conf'
    healthcheck:
      test:
        - 'CMD'
        - 'redis-cli'
        - '-h'
        - '127.0.0.1'
        - '-p'
        - '6379'
        - 'ping'
      interval: '30s'
      timeout: '5s'
      retries: 3
    read_only: true
    volumes:
      - '/tmp'
      - '/data'
    volumes_from:
      - 'helper:ro'
      - 'init:ro'
    ports:
      - '6379:6379'
